# Generated by Django 2.0.7 on 2018-07-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20180729_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='langauge',
            new_name='language',
        ),
    ]
